### PR TITLE
XHtml conformity

### PR DESCRIPTION
**Pull request by fiesh**
Dear Sergey,

As talked by email, here's the pull request ;)  New to github so didn't know that feature.

Best,
Christoph

Update: I fixed the bug, views work again and things seem fine!

### CODE REVIEW

**Comment by malyshev** [comment]
Please fix bugs in ajaxpanel (requests counter didn't works), when you want to add it to default list, and send a new pull requesr

**Comment by fiesh** [comment]
On 11/13/2012 06:19 AM, Sergey Malyshev wrote:

> Please fix bugs in ajaxpanel (requests counter didn't works), when you
> want to add it to default list, and send a new pull requesr
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/malyshev/yii-debug-toolbar/pull/62#issuecomment-10322997.

Sorry, they work fine for me, so I cannot reproduce this.

**Comment by fiesh** [comment]
OK, now I can reproduce it -- with the newest version of firefox.  This is very bizarre, under chromium and older versions of firefox it just works/worked fine.  I have no clue what is causing this, sorry.

**Comment by fiesh** [comment]
And I'm tempted to believe it's a firefox bug since not even the scrolling works any more...

**Comment by fiesh** [comment]
Actually, it also happens in the yii-debug-toolbar main branch, it's not a bug a I introduced.

**Comment by malyshev** [comment]
Closed as outdated

**Pull request closed without merging**
